"""
Green Fire — product seed script.
Run once to load all products into the database.
Safe to re-run — skips any slug that already exists.

Usage:
    python seed.py
"""

import json
import sys
import os
import re

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from app import create_app, db
from app.models import Product, ProductImage
from config import DevConfig


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _clean(val):
    """Return None for null-ish values: None, 'None', empty string."""
    if val is None or val == 'None' or val == '':
        return None
    return val


def _handle(instagram):
    """Normalise Instagram to a bare handle, stripping full URLs."""
    val = _clean(instagram)
    if not val:
        return None
    val = re.sub(r'https?://(www\.)?instagram\.com/', '', val).strip('/')
    return val or None


# ---------------------------------------------------------------------------
# Product data
# ---------------------------------------------------------------------------

PRODUCTS = [
    {
        "slug": "merc-alien-tech-minion",
        "name": "Alien-Tech Minion",
        "product_type": "heady",
        "subcategory": None,
        "series": None,
        "credit_label": "Artist",
        "credit": "Merc",
        "instagram": "minion_cca",
        "collab": None,
        "price_cents": 1500000,
        "height": "10 inches",
        "technique": None,
        "joint_size": "14mm",
        "glass_color": None,
        "glass_color_company": None,
        "gemstones": True,
        "electroform": False,
        "fume": False,
        "description": "",
        "is_sold": False,
        "is_active": True,
        "is_featured": False,
        "featured_order": None,
        "quantity": 1,
        "meta_description": None,
        "perc": None,
        "reclaimer": False,
        "includes": None,
        "variants": None,
        "attributes": None,
        "is_premium": False,
        "metal_type": None,
        "primary_image": "images/products/merc-alien-tech-minion/Merc_Minion_Green-Gold_1.jpg",
        "acquisition_type": "outright",
        "images": [
            "images/products/merc-alien-tech-minion/Merc_Minion_Green-Gold_1.jpg"
        ]
    },
    {
        "slug": "merc-blue-minion",
        "name": "Blue Minion",
        "product_type": "heady",
        "subcategory": None,
        "series": None,
        "credit_label": "Artist",
        "credit": "Merc",
        "instagram": "minion_cca",
        "collab": None,
        "price_cents": 1500000,
        "height": "10 inches",
        "technique": None,
        "joint_size": "14mm",
        "glass_color": None,
        "glass_color_company": None,
        "gemstones": True,
        "electroform": False,
        "fume": False,
        "description": "",
        "is_sold": False,
        "is_active": True,
        "is_featured": False,
        "featured_order": None,
        "quantity": 1,
        "meta_description": None,
        "perc": None,
        "reclaimer": False,
        "includes": None,
        "variants": None,
        "attributes": None,
        "is_premium": False,
        "metal_type": None,
        "primary_image": "images/products/merc-blue-minion/Merc_Minion_Blue_1.jpg",
        "acquisition_type": "outright",
        "images": [
            "images/products/merc-blue-minion/Merc_Minion_Blue_1.jpg"
        ]
    },
    {
        "slug": "jenkins-bonzai-tree",
        "name": "Bonzai Tree",
        "product_type": "heady",
        "subcategory": None,
        "series": None,
        "credit_label": "Artist",
        "credit": "Ryan Jenkins",
        "instagram": "thinkins_glass",
        "collab": None,
        "price_cents": 1000000,
        "height": "16 inches",
        "technique": None,
        "joint_size": "14mm",
        "glass_color": None,
        "glass_color_company": None,
        "gemstones": False,
        "electroform": True,
        "fume": False,
        "description": "",
        "is_sold": False,
        "is_active": True,
        "is_featured": False,
        "featured_order": None,
        "quantity": 1,
        "meta_description": None,
        "perc": None,
        "reclaimer": False,
        "includes": None,
        "variants": None,
        "attributes": None,
        "is_premium": False,
        "metal_type": None,
        "primary_image": "images/products/jenkins-bonzai-tree/Jenkins_Bonzai_1.jpg",
        "acquisition_type": "outright",
        "images": [
            "images/products/jenkins-bonzai-tree/Jenkins_Bonzai_1.jpg"
        ]
    },
    {
        "slug": "glassfish-ewok",
        "name": "Ewok",
        "product_type": "heady",
        "subcategory": None,
        "series": None,
        "credit_label": "Artist",
        "credit": "TheGlassFish13",
        "instagram": "theglassfish13",
        "collab": None,
        "price_cents": 1000000,
        "height": "8 inches",
        "technique": None,
        "joint_size": "14mm",
        "glass_color": None,
        "glass_color_company": None,
        "gemstones": False,
        "electroform": False,
        "fume": False,
        "description": "",
        "is_sold": False,
        "is_active": True,
        "is_featured": False,
        "featured_order": None,
        "quantity": 1,
        "meta_description": None,
        "perc": None,
        "reclaimer": False,
        "includes": None,
        "variants": None,
        "attributes": None,
        "is_premium": False,
        "metal_type": None,
        "primary_image": "images/products/glassfish-ewok/Ewok_1.jpg",
        "acquisition_type": "outright",
        "images": [
            "images/products/glassfish-ewok/Ewok_1.jpg",
            "images/products/glassfish-ewok/Ewok_2.jpg"
        ]
    },
    {
        "slug": "creep-ganesh",
        "name": "Ganesh",
        "product_type": "heady",
        "subcategory": None,
        "series": None,
        "credit_label": "Artist",
        "credit": "Creep",
        "instagram": "creepglass",
        "collab": None,
        "price_cents": 1350000,
        "height": "12 inches",
        "technique": None,
        "joint_size": "18mm",
        "glass_color": None,
        "glass_color_company": None,
        "gemstones": False,
        "electroform": False,
        "fume": False,
        "description": "",
        "is_sold": False,
        "is_active": True,
        "is_featured": False,
        "featured_order": None,
        "quantity": 1,
        "meta_description": None,
        "perc": None,
        "reclaimer": False,
        "includes": None,
        "variants": None,
        "attributes": None,
        "is_premium": False,
        "metal_type": None,
        "primary_image": "images/products/creep-ganesh/Creep_Ganesh_1.jpg",
        "acquisition_type": "outright",
        "images": [
            "images/products/creep-ganesh/Creep_Ganesh_1.jpg"
        ]
    },
    {
        "slug": "jedi-jack-skillington",
        "name": "Jack Skillington Rig",
        "product_type": "heady",
        "subcategory": None,
        "series": None,
        "credit_label": "Artist",
        "credit": "Jedi Glass",
        "instagram": "jediglassworks",
        "collab": None,
        "price_cents": 120000,
        "height": "14 inches",
        "technique": None,
        "joint_size": "14mm",
        "glass_color": None,
        "glass_color_company": None,
        "gemstones": False,
        "electroform": False,
        "fume": False,
        "description": "",
        "is_sold": False,
        "is_active": True,
        "is_featured": False,
        "featured_order": None,
        "quantity": 1,
        "meta_description": None,
        "perc": None,
        "reclaimer": False,
        "includes": None,
        "variants": None,
        "attributes": None,
        "is_premium": False,
        "metal_type": None,
        "primary_image": "images/products/jedi-jack-skillington/Jedi_Jack_1.jpg",
        "acquisition_type": "outright",
        "images": [
            "images/products/jedi-jack-skillington/Jedi_Jack_1.jpg"
        ]
    },
    {
        "slug": "opinicus-o-ring-rig",
        "name": "O-ring Rig",
        "product_type": "heady",
        "subcategory": None,
        "series": None,
        "credit_label": "Artist",
        "credit": "Opinicus",
        "instagram": "opinicus9",
        "collab": None,
        "price_cents": 800000,
        "height": "8 inches",
        "technique": "Sandblasting and frosting",
        "joint_size": "14mm",
        "glass_color": None,
        "glass_color_company": None,
        "gemstones": False,
        "electroform": False,
        "fume": True,
        "description": "",
        "is_sold": False,
        "is_active": True,
        "is_featured": False,
        "featured_order": None,
        "quantity": 1,
        "meta_description": None,
        "perc": None,
        "reclaimer": False,
        "includes": None,
        "variants": None,
        "attributes": None,
        "is_premium": False,
        "metal_type": None,
        "primary_image": "images/products/opinicus-o-ring-rig/Opinicus_1.jpg",
        "acquisition_type": "outright",
        "images": [
            "images/products/opinicus-o-ring-rig/Opinicus_1.jpg"
        ]
    },
    {
        "slug": "amy-likes-fire-purple-pony",
        "name": "Purple Pony",
        "product_type": "heady",
        "subcategory": None,
        "series": "Amy's Ponies",
        "credit_label": "Artist",
        "credit": "Amy Likes Fire",
        "instagram": "amylikesfire",
        "collab": None,
        "price_cents": 650000,
        "height": "7 inches",
        "technique": None,
        "joint_size": "14mm",
        "glass_color": None,
        "glass_color_company": None,
        "gemstones": True,
        "electroform": False,
        "fume": False,
        "description": "",
        "is_sold": True,
        "is_active": False,
        "is_featured": False,
        "featured_order": None,
        "quantity": 1,
        "meta_description": None,
        "perc": None,
        "reclaimer": False,
        "includes": None,
        "variants": None,
        "attributes": None,
        "is_premium": False,
        "metal_type": None,
        "primary_image": "images/products/amy-likes-fire-purple-pony/Amy_Likes_Fire_1.jpg",
        "acquisition_type": "outright",
        "images": [
            "images/products/amy-likes-fire-purple-pony/Amy_Likes_Fire_1.jpg"
        ]
    },
    {
        "slug": "jenkins-reef-rig",
        "name": "Reef Rig",
        "product_type": "heady",
        "subcategory": None,
        "series": None,
        "credit_label": "Artist",
        "credit": "Ryan Jenkins",
        "instagram": "thinkins_glass",
        "collab": None,
        "price_cents": 1500000,
        "height": "12 inches",
        "technique": None,
        "joint_size": "14mm",
        "glass_color": None,
        "glass_color_company": None,
        "gemstones": False,
        "electroform": True,
        "fume": False,
        "description": "",
        "is_sold": False,
        "is_active": True,
        "is_featured": False,
        "featured_order": None,
        "quantity": 1,
        "meta_description": None,
        "perc": None,
        "reclaimer": False,
        "includes": None,
        "variants": None,
        "attributes": None,
        "is_premium": False,
        "metal_type": None,
        "primary_image": "images/products/jenkins-reef-rig/Jenkins_Coral_1.jpg",
        "acquisition_type": "outright",
        "images": [
            "images/products/jenkins-reef-rig/Jenkins_Coral_1.jpg",
            "images/products/jenkins-reef-rig/Jenkins_Coral_2.jpg"
        ]
    },
    {
        "slug": "emperial-runtz-bottle",
        "name": "Runtz Swiss Baby Bottle",
        "product_type": "heady",
        "subcategory": None,
        "series": None,
        "credit_label": "Artist",
        "credit": "Emperial Glass",
        "instagram": "emperial1",
        "collab": "High-Tech",
        "price_cents": 750000,
        "height": "12 inches",
        "technique": "Swiss-perc",
        "joint_size": "14mm",
        "glass_color": None,
        "glass_color_company": None,
        "gemstones": False,
        "electroform": False,
        "fume": False,
        "description": "",
        "is_sold": False,
        "is_active": True,
        "is_featured": False,
        "featured_order": None,
        "quantity": 1,
        "meta_description": None,
        "perc": None,
        "reclaimer": False,
        "includes": None,
        "variants": None,
        "attributes": None,
        "is_premium": False,
        "metal_type": None,
        "primary_image": "images/products/emperial-runtz-bottle/Emperial_Runtz_1.jpg",
        "acquisition_type": "outright",
        "images": [
            "images/products/emperial-runtz-bottle/Emperial_Runtz_1.jpg",
            "images/products/emperial-runtz-bottle/Emperial_Runtz_2.jpg",
            "images/products/emperial-runtz-bottle/Emperial_Runtz_3.jpg"
        ]
    },
    {
        "slug": "emperial-sour-patch-kidz-bottle",
        "name": "Sour Patch Kidz Swiss Baby Bottle",
        "product_type": "heady",
        "subcategory": None,
        "series": None,
        "credit_label": "Artist",
        "credit": "Emperial Glass",
        "instagram": "emperial1",
        "collab": "High-Tech",
        "price_cents": 750000,
        "height": "12 inches",
        "technique": "Swiss-perc",
        "joint_size": "14mm",
        "glass_color": None,
        "glass_color_company": None,
        "gemstones": False,
        "electroform": False,
        "fume": False,
        "description": "",
        "is_sold": False,
        "is_active": True,
        "is_featured": False,
        "featured_order": None,
        "quantity": 1,
        "meta_description": None,
        "perc": None,
        "reclaimer": False,
        "includes": None,
        "variants": None,
        "attributes": None,
        "is_premium": False,
        "metal_type": None,
        "primary_image": "images/products/emperial-sour-patch-kidz-bottle/Emperial_SourPatchKids_1.jpg",
        "acquisition_type": "outright",
        "images": [
            "images/products/emperial-sour-patch-kidz-bottle/Emperial_SourPatchKids_1.jpg",
            "images/products/emperial-sour-patch-kidz-bottle/Emperial_SourPatchKids_2.jpg",
            "images/products/emperial-sour-patch-kidz-bottle/Emperial_SourPatchKids_3.jpg"
        ]
    },
    {
        "slug": "creep-totem",
        "name": "Totem",
        "product_type": "heady",
        "subcategory": None,
        "series": None,
        "credit_label": "Artist",
        "credit": "Creep",
        "instagram": "creepglass",
        "collab": None,
        "price_cents": 600000,
        "height": "12 inches",
        "technique": "Reticello",
        "joint_size": "14mm",
        "glass_color": None,
        "glass_color_company": None,
        "gemstones": False,
        "electroform": False,
        "fume": False,
        "description": "",
        "is_sold": False,
        "is_active": True,
        "is_featured": False,
        "featured_order": None,
        "quantity": 1,
        "meta_description": None,
        "perc": None,
        "reclaimer": False,
        "includes": None,
        "variants": None,
        "attributes": None,
        "is_premium": False,
        "metal_type": None,
        "primary_image": "images/products/creep-totem/Creep_Totem_1.jpg",
        "acquisition_type": "outright",
        "images": [
            "images/products/creep-totem/Creep_Totem_1.jpg"
        ]
    },
    # --- PRODO ---
    {
        "slug": "borofarm-bell-rig",
        "name": "BoroFarm Bell Rig",
        "product_type": "prodo",
        "subcategory": "oil-rigs",
        "series": None,
        "credit_label": "Brand",
        "credit": "BoroFarm",
        "instagram": "borofarm",
        "collab": None,
        "price_cents": 25000,
        "height": "8 inches",
        "technique": None,
        "joint_size": "14mm",
        "glass_color": None,
        "glass_color_company": None,
        "gemstones": False,
        "electroform": False,
        "fume": False,
        "description": "",
        "is_sold": False,
        "is_active": True,
        "is_featured": False,
        "featured_order": None,
        "quantity": 1,
        "meta_description": None,
        "perc": "Showerhead",
        "reclaimer": False,
        "includes": "Quartz nail",
        "variants": None,
        "attributes": None,
        "is_premium": False,
        "metal_type": None,
        "primary_image": "images/products/borofarm-bell-rig/BoroFarmBubblerRig_1.webp",
        "acquisition_type": "outright",
        "images": [
            "images/products/borofarm-bell-rig/BoroFarmBubblerRig_1.webp"
        ]
    },
    {
        "slug": "joshmann-banger-ground-joint",
        "name": "J-Mann Banger w/ Ground Joint",
        "product_type": "prodo",
        "subcategory": "oil-rigs",
        "series": None,
        "credit_label": "Artist",
        "credit": "Josh Mann",
        "instagram": "joshmann_glass",
        "collab": None,
        "price_cents": 15000,
        "height": "8 inches",
        "technique": None,
        "joint_size": "14mm Ground Joint",
        "glass_color": None,
        "glass_color_company": None,
        "gemstones": False,
        "electroform": False,
        "fume": False,
        "description": "",
        "is_sold": False,
        "is_active": True,
        "is_featured": True,
        "featured_order": None,
        "quantity": 1,
        "meta_description": None,
        "perc": "Three hole diffusion",
        "reclaimer": False,
        "includes": "14mm Quartz Nail",
        "variants": None,
        "attributes": None,
        "is_premium": False,
        "metal_type": None,
        "primary_image": "images/products/joshmann-banger-ground-joint/joshmann_14mm_ground-joint_1.jpg",
        "acquisition_type": "outright",
        "images": [
            "images/products/joshmann-banger-ground-joint/joshmann_14mm_ground-joint_1.jpg",
            "images/products/joshmann-banger-ground-joint/joshmann_14mm_ground-joint_2.jpg"
        ]
    },
    {
        "slug": "j-mann-banger-w-reclaimer",
        "name": "J-Mann Banger w/ Reclaimer",
        "product_type": "prodo",
        "subcategory": "oil-rigs",
        "series": None,
        "credit_label": "Artist",
        "credit": "Josh Mann",
        "instagram": "joshmann_glass",
        "collab": None,
        "price_cents": 14998,
        "height": "8 inches",
        "technique": None,
        "joint_size": "14mm",
        "glass_color": None,
        "glass_color_company": None,
        "gemstones": False,
        "electroform": False,
        "fume": False,
        "description": "",
        "is_sold": False,
        "is_active": True,
        "is_featured": True,
        "featured_order": None,
        "quantity": 5,
        "meta_description": None,
        "perc": None,
        "reclaimer": True,
        "includes": "Quartz Nail",
        "variants": None,
        "attributes": None,
        "is_premium": False,
        "metal_type": None,
        "primary_image": "images/products/j-mann-banger-w-reclaimer/j-mann-banger-w-reclaimer_1.jpg",
        "acquisition_type": "outright",
        "images": [
            "images/products/j-mann-banger-w-reclaimer/j-mann-banger-w-reclaimer_1.jpg"
        ]
    },
    {
        "slug": "joshmann-clear-banger",
        "name": "J-Mann Clear Banger",
        "product_type": "prodo",
        "subcategory": "oil-rigs",
        "series": None,
        "credit_label": "Artist",
        "credit": "Josh Mann",
        "instagram": "joshmann_glass",
        "collab": None,
        "price_cents": 15000,
        "height": "8 inches",
        "technique": None,
        "joint_size": "14mm",
        "glass_color": None,
        "glass_color_company": None,
        "gemstones": False,
        "electroform": False,
        "fume": False,
        "description": "",
        "is_sold": False,
        "is_active": True,
        "is_featured": True,
        "featured_order": None,
        "quantity": 1,
        "meta_description": None,
        "perc": "Three hole diffusion",
        "reclaimer": False,
        "includes": "14mm Quartz Nail",
        "variants": None,
        "attributes": None,
        "is_premium": False,
        "metal_type": None,
        "primary_image": "images/products/joshmann-clear-banger/joshmann_clear_rig_1.jpg",
        "acquisition_type": "outright",
        "images": [
            "images/products/joshmann-clear-banger/joshmann_clear_rig_1.jpg",
            "images/products/joshmann-clear-banger/joshmann_clear_rig_2.jpg"
        ]
    },
    {
        "slug": "joshmann-gold-fume-banger",
        "name": "J-Mann Gold Fume Banger",
        "product_type": "prodo",
        "subcategory": "oil-rigs",
        "series": None,
        "credit_label": "Artist",
        "credit": "Josh Mann",
        "instagram": "joshmann_glass",
        "collab": None,
        "price_cents": 15000,
        "height": "8 inches",
        "technique": None,
        "joint_size": "14mm",
        "glass_color": None,
        "glass_color_company": None,
        "gemstones": False,
        "electroform": False,
        "fume": True,
        "description": "",
        "is_sold": False,
        "is_active": True,
        "is_featured": True,
        "featured_order": None,
        "quantity": 1,
        "meta_description": None,
        "perc": "Three hole diffusion",
        "reclaimer": False,
        "includes": "14mm Quartz Nail",
        "variants": None,
        "attributes": None,
        "is_premium": False,
        "metal_type": None,
        "primary_image": "images/products/joshmann-gold-fume-banger/joshmann_gold_fume_1.jpg",
        "acquisition_type": "outright",
        "images": [
            "images/products/joshmann-gold-fume-banger/joshmann_gold_fume_1.jpg",
            "images/products/joshmann-gold-fume-banger/joshmann_gold_fume_2.jpg"
        ]
    },
    {
        "slug": "joshmann-spoons",
        "name": "J-Mann Spoons",
        "product_type": "prodo",
        "subcategory": "dry-pipes",
        "series": None,
        "credit_label": "Artist",
        "credit": "Josh Mann",
        "instagram": "joshmann_glass",
        "collab": None,
        "price_cents": 2800,
        "height": "4.5 inches",
        "technique": None,
        "joint_size": None,
        "glass_color": None,
        "glass_color_company": None,
        "gemstones": False,
        "electroform": False,
        "fume": False,
        "description": "",
        "is_sold": False,
        "is_active": True,
        "is_featured": False,
        "featured_order": None,
        "quantity": 1,
        "meta_description": None,
        "perc": "Carb hole",
        "reclaimer": False,
        "includes": None,
        "variants": [
            "Orange", "Red", "Green", "Blue", "Purple",
            "Yellow", "Black", "Gold Fume", "Silver Fume"
        ],
        "attributes": None,
        "is_premium": False,
        "metal_type": None,
        "primary_image": "images/products/joshmann-spoons/joshmann_spoons_1.jpg",
        "acquisition_type": "outright",
        "images": [
            "images/products/joshmann-spoons/joshmann_spoons_1.jpg"
        ]
    },
    {
        "slug": "joshmann-straight-rig",
        "name": "J-Mann Straight Rig",
        "product_type": "prodo",
        "subcategory": "oil-rigs",
        "series": None,
        "credit_label": "Artist",
        "credit": "Josh Mann",
        "instagram": "joshmann_glass",
        "collab": None,
        "price_cents": 15000,
        "height": "8 inches",
        "technique": None,
        "joint_size": "14mm",
        "glass_color": None,
        "glass_color_company": None,
        "gemstones": False,
        "electroform": False,
        "fume": True,
        "description": "",
        "is_sold": False,
        "is_active": True,
        "is_featured": True,
        "featured_order": None,
        "quantity": 1,
        "meta_description": None,
        "perc": "Three hole diffusion",
        "reclaimer": False,
        "includes": "14mm Quartz Nail",
        "variants": None,
        "attributes": None,
        "is_premium": False,
        "metal_type": None,
        "primary_image": "images/products/joshmann-straight-rig/joshmann_upright_1.jpg",
        "acquisition_type": "outright",
        "images": [
            "images/products/joshmann-straight-rig/joshmann_upright_1.jpg",
            "images/products/joshmann-straight-rig/joshmann_upright_2.jpg"
        ]
    },
    {
        "slug": "sherlock",
        "name": "Sherlock",
        "product_type": "prodo",
        "subcategory": "dry-pipes",
        "series": None,
        "credit_label": "Artist",
        "credit": "Josh Mann",
        "instagram": "joshmann_glass",
        "collab": None,
        "price_cents": 7999,
        "height": "8 inches",
        "technique": None,
        "joint_size": None,
        "glass_color": None,
        "glass_color_company": None,
        "gemstones": False,
        "electroform": False,
        "fume": False,
        "description": "",
        "is_sold": False,
        "is_active": True,
        "is_featured": True,
        "featured_order": 2,
        "quantity": 5,
        "meta_description": None,
        "perc": None,
        "reclaimer": False,
        "includes": None,
        "variants": ["Blue", "Green", "Red", "Orange", "Purple"],
        "attributes": None,
        "is_premium": False,
        "metal_type": None,
        "primary_image": "images/products/sherlock/sherlock_1.jpg",
        "acquisition_type": "outright",
        "images": [
            "images/products/sherlock/sherlock_1.jpg"
        ]
    },
    # --- VAPES ---
    {
        "slug": "airopro-vape-battery",
        "name": "AiroPro Vape Battery",
        "product_type": "vape",
        "subcategory": "vaporizers",
        "series": None,
        "credit_label": "Brand",
        "credit": "AiroPro",
        "instagram": "airobrands",
        "collab": None,
        "price_cents": 6000,
        "height": "4 inches",
        "technique": None,
        "joint_size": None,
        "glass_color": None,
        "glass_color_company": None,
        "gemstones": False,
        "electroform": False,
        "fume": False,
        "description": "The AiroPro vaporizer uses a proprietary magnetic pod system that eliminates leakage and delivers consistent, high-volume vapor per draw.",
        "is_sold": False,
        "is_active": True,
        "is_featured": False,
        "featured_order": None,
        "quantity": 20,
        "meta_description": None,
        "perc": None,
        "reclaimer": False,
        "includes": None,
        "variants": None,
        "attributes": None,
        "is_premium": True,
        "metal_type": None,
        "primary_image": "images/products/airopro-vape-battery/airopro-vape-battery_1.jpg",
        "acquisition_type": "outright",
        "images": [
            "images/products/airopro-vape-battery/airopro-vape-battery_1.jpg",
            "images/products/airopro-vape-battery/airopro-vape-battery_2.jpg"
        ]
    },
    {
        "slug": "pbi-vape-battery",
        "name": "PBI Vape Battery",
        "product_type": "vape",
        "subcategory": "oil-accessories",
        "series": None,
        "credit_label": "Brand",
        "credit": "Hamilton Devices",
        "instagram": None,
        "collab": None,
        "price_cents": 7500,
        "height": None,
        "technique": None,
        "joint_size": None,
        "glass_color": None,
        "glass_color_company": None,
        "gemstones": False,
        "electroform": False,
        "fume": False,
        "description": "",
        "is_sold": False,
        "is_active": True,
        "is_featured": False,
        "featured_order": None,
        "quantity": 8,
        "meta_description": None,
        "perc": None,
        "reclaimer": False,
        "includes": None,
        "variants": None,
        "attributes": ["510 thread", "900 mAh"],
        "is_premium": False,
        "metal_type": None,
        "primary_image": "images/products/pbi-vape-battery/PBI_vape_1.jpg",
        "acquisition_type": "outright",
        "images": [
            "images/products/pbi-vape-battery/PBI_vape_1.jpg",
            "images/products/pbi-vape-battery/PBI_vape_2.webp",
            "images/products/pbi-vape-battery/PBI_vape_3.jpg"
        ]
    },
    {
        "slug": "gf-510-thread-battery",
        "name": "Screw-on 510 Thread Vape Battery",
        "product_type": "vape",
        "subcategory": "vaporizers",
        "series": None,
        "credit_label": "Brand",
        "credit": "Green Fire",
        "instagram": None,
        "collab": None,
        "price_cents": 2000,
        "height": None,
        "technique": None,
        "joint_size": None,
        "glass_color": None,
        "glass_color_company": None,
        "gemstones": False,
        "electroform": False,
        "fume": False,
        "description": "",
        "is_sold": False,
        "is_active": True,
        "is_featured": False,
        "featured_order": None,
        "quantity": 10,
        "meta_description": None,
        "perc": None,
        "reclaimer": False,
        "includes": "Micro-USB Cable",
        "variants": None,
        "attributes": ["900 mAh"],
        "is_premium": False,
        "metal_type": None,
        "primary_image": "images/products/gf-510-thread-battery/GF_510-thread_1.jpg",
        "acquisition_type": "outright",
        "images": [
            "images/products/gf-510-thread-battery/GF_510-thread_1.jpg",
            "images/products/gf-510-thread-battery/GF_510-thread_2.jpg",
            "images/products/gf-510-thread-battery/GF_510-thread_3.jpg",
            "images/products/gf-510-thread-battery/GF_510-thread_4.jpg",
            "images/products/gf-510-thread-battery/GF_510-thread_5.jpg",
            "images/products/gf-510-thread-battery/GF_510-thread_6.png"
        ]
    },
    # --- TOOLS / ACCESSORIES ---
    {
        "slug": "quartz-banger-14mm",
        "name": "Quartz Banger 14mm",
        "product_type": "tool",
        "subcategory": "oil-accessories",
        "series": None,
        "credit_label": None,
        "credit": None,
        "instagram": None,
        "collab": None,
        "price_cents": 1999,
        "height": None,
        "technique": None,
        "joint_size": "14mm",
        "glass_color": None,
        "glass_color_company": None,
        "gemstones": False,
        "electroform": False,
        "fume": False,
        "description": "",
        "is_sold": False,
        "is_active": True,
        "is_featured": False,
        "featured_order": None,
        "quantity": 200,
        "meta_description": None,
        "perc": None,
        "reclaimer": False,
        "includes": None,
        "variants": None,
        "attributes": None,
        "is_premium": False,
        "metal_type": None,
        "primary_image": "images/products/quartz-banger-14mm/quartz-banger-14mm_1.jpg",
        "acquisition_type": "outright",
        "images": [
            "images/products/quartz-banger-14mm/quartz-banger-14mm_1.jpg"
        ]
    },
]


# ---------------------------------------------------------------------------
# Seed
# ---------------------------------------------------------------------------

def seed():
    app = create_app(DevConfig)
    with app.app_context():
        added   = 0
        skipped = 0

        for item in PRODUCTS:
            if Product.query.filter_by(slug=item['slug']).first():
                print(f'  SKIP  {item["slug"]}')
                skipped += 1
                continue

            variants   = item.get('variants')
            attributes = item.get('attributes')

            product = Product(
                slug                 = item['slug'],
                name                 = item['name'],
                product_type         = item['product_type'],
                subcategory          = _clean(item.get('subcategory')),
                series               = _clean(item.get('series')),
                credit_label         = _clean(item.get('credit_label')),
                credit               = _clean(item.get('credit')),
                instagram            = _handle(item.get('instagram')),
                collab               = _clean(item.get('collab')),
                price_cents          = item['price_cents'],
                height               = _clean(item.get('height')),
                technique            = _clean(item.get('technique')),
                joint_size           = _clean(item.get('joint_size')),
                glass_color          = _clean(item.get('glass_color')),
                glass_color_company  = _clean(item.get('glass_color_company')),
                gemstones            = item.get('gemstones', False),
                electroform          = item.get('electroform', False),
                fume                 = item.get('fume', False),
                description          = item.get('description') or '',
                is_sold              = item.get('is_sold', False),
                is_active            = item.get('is_active', True),
                is_featured          = item.get('is_featured', False),
                featured_order       = item.get('featured_order'),
                quantity             = item.get('quantity', 1),
                meta_description     = _clean(item.get('meta_description')),
                perc                 = _clean(item.get('perc')),
                reclaimer            = item.get('reclaimer', False),
                includes             = _clean(item.get('includes')),
                variants_json        = json.dumps(variants) if variants else None,
                attributes_json      = json.dumps(attributes) if attributes else None,
                is_premium           = item.get('is_premium', False),
                metal_type           = _clean(item.get('metal_type')),
                primary_image        = item.get('primary_image'),
                acquisition_type     = item.get('acquisition_type', 'outright'),
            )
            db.session.add(product)
            db.session.flush()

            for i, img_url in enumerate(item.get('images', [])):
                db.session.add(ProductImage(
                    product_id = product.id,
                    image_url  = img_url,
                    alt_text   = item['name'],
                    sort_order = i,
                ))

            print(f'  ADD   {item["slug"]}')
            added += 1

        db.session.commit()
        print(f'\nDone — {added} added, {skipped} skipped.')


if __name__ == '__main__':
    seed()
