"""add display_order and notes to product

Revision ID: 15ed1e9712c0
Revises: b2d4f6a8c001
Create Date: 2026-04-30 15:18:15.543256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15ed1e9712c0'
down_revision = 'b2d4f6a8c001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('display_order', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('notes')
        batch_op.drop_column('display_order')

    # ### end Alembic commands ###
