"""Add Product model fields

Revision ID: 2ad8015d7bdc
Revises: 509085280963
Create Date: 2026-04-15 20:38:33.774810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ad8015d7bdc'
down_revision = '509085280963'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subcategory', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('credit_label', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('credit', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('instagram', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('series', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('glass_color', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('glass_color_company', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('gemstones', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('electroform', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('fume', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('collab', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('perc', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('reclaimer', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('includes', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('metal_type', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('is_premium', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('variants_json', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('attributes_json', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('attributes_json')
        batch_op.drop_column('variants_json')
        batch_op.drop_column('is_premium')
        batch_op.drop_column('metal_type')
        batch_op.drop_column('includes')
        batch_op.drop_column('reclaimer')
        batch_op.drop_column('perc')
        batch_op.drop_column('collab')
        batch_op.drop_column('fume')
        batch_op.drop_column('electroform')
        batch_op.drop_column('gemstones')
        batch_op.drop_column('glass_color_company')
        batch_op.drop_column('glass_color')
        batch_op.drop_column('series')
        batch_op.drop_column('instagram')
        batch_op.drop_column('credit')
        batch_op.drop_column('credit_label')
        batch_op.drop_column('subcategory')

    # ### end Alembic commands ###
