"""add quantity to product

Revision ID: 6b855672deed
Revises: 3252f6d2e00f
Create Date: 2026-04-17 20:48:53.113291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b855672deed'
down_revision = '3252f6d2e00f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column(
            'quantity', sa.Integer(), nullable=False, server_default='1'
        ))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('quantity')

    # ### end Alembic commands ###
